name: auto-study

on:
  workflow_dispatch:
  
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    
    - name: Pip requirements
      run: |
        pip3 install requests pycryptodome
         
    - name: auto study
      run: |
        python3 workflow.py <<EOF
        ${{secrets.USERNAME}}
        ${{secrets.PWD}}
        ${{secrets.PUB_KEY}}
        ${{secrets.OCR_API_KEY}}
        ${{secrets.OCR_SECRET_KEY}}
        EOF
        
